name: rssnr2
channels:
  - conda-forge
  - defaults
dependencies:
  - python[version='>=3.10']
  - pip
  - conda[version='>=23.11.0']
  - mamba[version='>=1.5.5']
  - bs4
  - ca-certificates
  - certifi
  - openssl
  - pandas
  - scipy
  - matplotlib
  - pyproj
  - h5py
  - numpy
  - ipykernel
  - xarray
  - netcdf4
  - cartopy
  - seaborn
  - dask
  - pymc
  - corner
  - ipywidgets

